"""P0.4 (cascor#573): the log-record envelope and named-marker contract, enforced in cascor CI.

Project:     juniper-cascor
Sub-Project: logging
Author:      Paul Calnon
License:     MIT License

WHY THIS FILE EXISTS
cascor's log records are parsed by scripts in juniper-ml: they split worker from parent records
on the ``+`` sentinel, parse the ``(timestamp)`` -- three of them only at SECOND resolution --
anchor on the ``func:LINE]`` prefix, and match 34 distinct message markers such as
``fit: Training completed.``. Every one of those breakages is invisible here: change the message,
drop the sentinel or add milliseconds, and cascor's suite stays green while the analysis tooling
silently stops matching. A test in juniper-ml cannot fail a cascor PR -- separate repositories, no
status-check propagation -- so the contract has to be enforced HERE (roadmap P0.4(d) option (i),
in juniper-ml ``notes/JUNIPER_2026-09-02_JUNIPER-CASCOR_LOGGING-REDESIGN-ROADMAP.md`` §3.1).

WHAT IT PINS, AND HOW EACH PART CAN FAIL

1. **The formatter goldens** -- Path A's constants, Path B's whole ``conf/logging_config.yaml``
   (levels and handlers too: setting the ``juniper`` logger to WARNING would delete every
   run-verdict marker, since those are INFO records), and Path C's installed handlers, including
   the rotation parameters juniper-ml globs against.
2. **The real emit path** -- a CHILD PROCESS (``helpers/log_envelope_emitter.py``) drives all
   three writers into one file. It has to be a child: ``conftest.py``'s session-scoped
   ``_cache_logging_system`` replaces ``Logger._log_at_level`` with a no-op for the whole session,
   so any in-process emit would pass whatever the envelope looked like. Records are compared
   byte-for-byte (modulo the timestamp VALUE, whose FORMAT and precision are checked), and each
   record's ``func:LINE`` against the emitter's own AST -- which makes this the detector for
   roadmap P2.1 (moving frame capture inside ``_log_at_level``).
3. **The named markers** -- every message fragment juniper-ml anchors on must still exist, IN
   ORDER, in one string literal of the file that emits it, inside a logger call at or above the
   level the consumers rely on. ``fixtures/log_envelope/marker_inventory.json`` is generated by
   juniper-ml ``util/ad-hoc/2026-09-22_p04_log_marker_census.py`` and names every consumer.
4. **The checker itself** -- negative controls prove it can say NO: a broken record must fail
   to classify. Without them a regex loose enough to accept anything would pass every test above.

WHEN THIS FAILS
Read ``fixtures/log_envelope/README.md``. A failure here means juniper-ml tooling will stop
matching; the message names the consumers. Update the consumer (and regenerate the inventory) in
the same change, or do not make the change. To re-capture after an INTENDED envelope change:
``LOG_ENVELOPE_CAPTURE=1 pytest src/tests/unit/test_log_record_envelope_contract.py`` rewrites the
golden, then review the diff.
"""

from __future__ import annotations

import ast
import datetime
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
import yaml
from helpers import log_envelope as envelope
from helpers import log_envelope_emitter as emitter

# CI's unit lane runs ``pytest -m "unit and not slow" src/tests/unit`` (.github/workflows/ci.yml),
# so a test here without the ``unit`` marker is collected and then silently DESELECTED -- the job
# still reports success. Module-level, so it covers every test in this file.
pytestmark = pytest.mark.unit

_SRC = Path(__file__).resolve().parents[2]
_REPO = _SRC.parent
_FIXTURES = _SRC / "tests" / "fixtures" / "log_envelope"
_GOLDEN_PATH = _FIXTURES / "envelope_golden.json"
_EMITTER = Path(emitter.__file__).resolve()
_CAPTURE = os.environ.get("LOG_ENVELOPE_CAPTURE") == "1"

GOLDEN = json.loads(_GOLDEN_PATH.read_text(encoding="utf-8")) if _GOLDEN_PATH.is_file() or not _CAPTURE else {}
INVENTORY = json.loads((_FIXTURES / "marker_inventory.json").read_text(encoding="utf-8"))
REFERENCE = json.loads((_FIXTURES / "reference_captures.json").read_text(encoding="utf-8"))

_TS_FORMAT = "%Y-%m-%d %H:%M:%S"
_MARK = "P0.4 reference record: "


def _golden_section(key: str, observed, subkey: str | None = None):
    """Compare *observed* to ``GOLDEN[key]`` (or ``GOLDEN[key][subkey]``), or rewrite it in capture mode."""
    if _CAPTURE:
        if subkey is None:
            GOLDEN[key] = observed
        else:
            GOLDEN.setdefault(key, {})[subkey] = observed
        _GOLDEN_PATH.write_text(json.dumps(GOLDEN, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        pytest.skip(f"LOG_ENVELOPE_CAPTURE=1: rewrote {key!r} in {_GOLDEN_PATH.name}")
    want = GOLDEN[key] if subkey is None else GOLDEN[key][subkey]
    where = f"{key}/{subkey}" if subkey else key
    assert observed == want, f"the {where!r} envelope contract changed.\n  golden:   {want!r}\n  observed: {observed!r}\njuniper-ml parses this surface (see {_FIXTURES.relative_to(_REPO)}/README.md). If the change is intended, update the consumers and re-capture with LOG_ENVELOPE_CAPTURE=1."


def _expected_calls(func_name: str) -> list[tuple[int, str, str]]:
    """(line, method, rendered message) for each single-line call in ``emitter.<func_name>``."""
    tree = ast.parse(_EMITTER.read_text(encoding="utf-8"))
    func = next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == func_name)
    out = []
    for stmt in func.body:
        call = stmt.value if isinstance(stmt, ast.Expr) else None
        if not isinstance(call, ast.Call) or not isinstance(call.func, ast.Attribute):
            continue
        first = call.args[0]
        if isinstance(first, ast.Constant):
            message = first.value
        else:  # the %-args record: PERCENT_ARGS_TEMPLATE, *PERCENT_ARGS_VALUES
            message = emitter.PERCENT_ARGS_TEMPLATE % emitter.PERCENT_ARGS_VALUES
        out.append((call.lineno, call.func.attr, message))
    assert out, f"no calls found in {func_name} -- the emitter's AST contract is broken"
    return out


@pytest.fixture(scope="module")
def emitted(tmp_path_factory):
    """Run the emitter ONCE per module in a fresh interpreter; return every sink it wrote."""
    root = tmp_path_factory.mktemp("log_envelope")
    log_dir = root / "logs"
    report_path = root / "report.json"
    env = {k: v for k, v in os.environ.items() if k not in {"CASCOR_LOG_LEVEL", "JUNIPER_CASCOR_LOG_LEVEL"}}
    env["JUNIPER_CASCOR_LOG_DIR"] = str(log_dir)
    t0 = datetime.datetime.now().replace(microsecond=0) - datetime.timedelta(seconds=1)
    proc = subprocess.run(  # nosec B603 -- fixed interpreter, repo-local script, no user input
        [sys.executable, str(_EMITTER), str(report_path)],
        cwd=_SRC,
        env=env,
        capture_output=True,
        text=True,
        timeout=50,
    )
    t1 = datetime.datetime.now() + datetime.timedelta(seconds=1)
    assert proc.returncode == 0, f"emitter failed: rc={proc.returncode}\nstderr tail:\n{proc.stderr[-3000:]}"
    report = json.loads(report_path.read_text(encoding="utf-8"))
    log_file = Path(report["path_a"]["logging_file"])
    assert log_file.parent == log_dir, f"the file sink is {log_file}, not inside {log_dir}: the JUNIPER_CASCOR_LOG_DIR override did not reach the logger"
    assert log_file.is_file(), f"no file sink at {log_file}"
    return {
        "stdout": proc.stdout.splitlines(),
        "stderr": proc.stderr.splitlines(),
        "file": log_file.read_text(encoding="utf-8").splitlines(),
        "report": report,
        "log_dir": log_dir,
        "window": (t0, t1),
    }


def _ours(lines: list[str]) -> list[str]:
    return [line for line in lines if _MARK in line]


def _check_ts(ts: str, window) -> None:
    parsed = datetime.datetime.strptime(ts, _TS_FORMAT)  # raises on ANY other precision or layout
    assert window[0] <= parsed <= window[1], f"timestamp {ts} is outside the run window {window}"


# ---------------------------------------------------------------------------------------------------
# 1. Formatter goldens
# ---------------------------------------------------------------------------------------------------


class TestFormatterGoldens:
    def test_path_a_constants_and_the_values_the_logger_actually_uses(self):
        from cascor_constants.constants import _PROJECT_LOG_DATE_FORMAT, _PROJECT_LOG_FILE_NAME
        from cascor_constants.constants_logging.constants_logging import _LOGGER_LOG_FORMATTER_STRING_CONSOLE, _LOGGER_LOG_FORMATTER_STRING_FILE
        from log_config.logger.logger import Logger

        # The constants AND the class attributes: the emit path reads the latter, and a refactor
        # that re-points one without the other must not pass.
        assert Logger._formatter_string_file == _LOGGER_LOG_FORMATTER_STRING_FILE
        assert Logger._formatter_string_console == _LOGGER_LOG_FORMATTER_STRING_CONSOLE
        assert Logger._date_format == _PROJECT_LOG_DATE_FORMAT
        # The ``+`` sentinel is NOT here: it is written by the emit CODE (``print(f"+{...}")`` in
        # ``_log_at_level``), not by any formatter, so only the real-emit-path tests can pin it.
        observed = {
            "formatter_string_file": Logger._formatter_string_file,
            "formatter_string_console": Logger._formatter_string_console,
            "date_format": Logger._date_format,
            "log_file_name": _PROJECT_LOG_FILE_NAME,
            "field_names_file": list(Logger._field_names_file),
            "field_names_console": list(Logger._field_names_console),
        }
        _golden_section("path_a", observed)

    def test_path_b_yaml_is_pinned_whole(self):
        # Whole, not just the two format strings: the handler and logger LEVELS decide whether the
        # run-verdict markers (INFO records on the ``juniper`` logger) reach the file at all.
        observed = yaml.safe_load((_REPO / "conf" / "logging_config.yaml").read_text(encoding="utf-8"))
        _golden_section("path_b_yaml", observed)

    def test_path_b_installed_handlers(self, emitted):
        _golden_section("path_b_installed", emitted["report"]["path_b"])

    def test_path_c_installed_handlers_including_rotation(self, emitted):
        _golden_section("path_c_installed", emitted["report"]["path_c"])


# ---------------------------------------------------------------------------------------------------
# 2. The real emit path
# ---------------------------------------------------------------------------------------------------


class TestRealEmitPath:
    def test_all_three_writers_share_one_file_in_the_override_dir(self, emitted):
        # juniper-ml globs ``logs/juniper_cascor.log*`` (RECON N-4, ~17 consumers); the three writers
        # sharing ONE name, one of which rotates it, is the N-9 hazard P3.3 exists to settle.
        name = GOLDEN["path_a"]["log_file_name"]
        assert Path(emitted["report"]["path_a"]["logging_file"]) == emitted["log_dir"] / name
        file_handlers = [h for section in ("path_b", "path_c") for h in emitted["report"][section]["handlers"] if "filename" in h]
        assert [h["filename"] for h in file_handlers] == [name, name], file_handlers

    @pytest.mark.parametrize("sink,shape", [("file", "A_FILE"), ("stdout", "A_CONSOLE")])
    def test_path_a_records_are_byte_exact_in_both_sinks(self, emitted, sink, shape):
        lines = [line for line in _ours(emitted[sink]) if line.startswith("+")]
        expected = _expected_calls("emit_path_a")
        assert len(lines) == len(expected), f"{sink}: expected {len(expected)} Path A records, got {len(lines)}:\n" + "\n".join(lines)
        for line, (lineno, method, message) in zip(lines, expected, strict=True):
            got_shape, match = envelope.classify(line)
            assert got_shape == shape, f"{sink}: not a {shape} record: {line!r}"
            _check_ts(match.group("ts"), emitted["window"])
            want = envelope.render_path_a("file" if sink == "file" else "console", file=_EMITTER.name, func="emit_path_a", line=lineno, ts=match.group("ts"), level=method.upper(), msg=message)
            assert line == want, f"{sink} record differs from the contract:\n  want {want!r}\n  got  {line!r}"

    def test_path_a_resolves_the_real_caller(self, emitted):
        # Stated separately from the byte-exact test so a P2.1 regression fails with a message
        # that says what is wrong, rather than as a diff of two long lines.
        records = [envelope.classify(line)[1] for line in _ours(emitted["file"]) if line.startswith("+")]
        funcs = sorted({m.group("func") for m in records})
        assert funcs == ["emit_path_a"], f"Path A records name {funcs} as their caller, not 'emit_path_a'. If you are moving frame capture inside _log_at_level (roadmap P2.1), pass cls._frm().f_back from _log_at_level and leave _frame_info's one-hop contract alone (test_logger_frame_resolution.py pins it)."

    def test_stdout_carries_only_records(self, emitted):
        # juniper-ml's launchers redirect stdout into a file its tools parse line by line; a stray
        # print() lands there as an unparseable line.
        strays = [line for line in emitted["stdout"] if envelope.classify(line)[0] not in ("A_CONSOLE", "STD_CONSOLE")]
        assert strays == [], f"non-record lines on stdout: {strays}"
        assert len(emitted["stdout"]) >= len(_expected_calls("emit_path_a")), "stdout is (nearly) empty -- a check over zero lines proves nothing"

    def test_path_b_file_records(self, emitted):
        lines = [line for line in _ours(emitted["file"]) if "path B" in line]
        expected = [call for call in _expected_calls("emit_path_b") if call[1] != "debug"]
        assert len(lines) == len(expected), f"expected {len(expected)} Path B records (DEBUG suppressed by the juniper logger's INFO level), got:\n" + "\n".join(lines)
        for line, (lineno, method, message) in zip(lines, expected, strict=True):
            shape, match = envelope.classify(line)
            assert shape == "STD_FILE_S", f"not a second-resolution stdlib file record: {line!r}"
            _check_ts(match.group("ts"), emitted["window"])
            assert (match.group("file"), match.group("func"), int(match.group("line")), match.group("level"), match.group("msg")) == (_EMITTER.name, "emit_path_b", lineno, method.upper(), message)

    def test_path_b_error_also_reaches_stdout_with_a_two_digit_year(self, emitted):
        lineno, _method, message = next(call for call in _expected_calls("emit_path_b") if call[1] == "error")
        lines = [line for line in _ours(emitted["stdout"]) if "path B" in line]
        assert len(lines) == 1, lines
        match = envelope.STD_CONSOLE.match(lines[0])
        assert match, f"not the conf/logging_config.yaml console shape: {lines[0]!r}"
        assert (match.group("file"), int(match.group("line")), match.group("level"), match.group("msg")) == (_EMITTER.name, lineno, "ERROR", message)

    def test_path_c_file_record_has_millisecond_precision(self, emitted):
        lines = [line for line in _ours(emitted["file"]) if "path C" in line]
        expected = [call for call in _expected_calls("emit_path_c") if call[1] != "debug"]
        assert len(lines) == len(expected), lines
        shape, match = envelope.classify(lines[0])
        assert shape == "STD_FILE_MS", f"Path C's RotatingFileHandler has no datefmt, so its records carry ',mmm': {lines[0]!r}"
        assert (match.group("func"), int(match.group("line"))) == ("emit_path_c", expected[0][0])


# ---------------------------------------------------------------------------------------------------
# 3. Named markers
# ---------------------------------------------------------------------------------------------------


class TestMarkerInventory:
    def test_inventory_is_well_formed(self):
        assert INVENTORY["generated_by"].endswith("2026-09-22_p04_log_marker_census.py")
        seen = set()
        for marker in INVENTORY["markers"]:
            key = tuple(marker["fragments"])
            assert key and key not in seen, f"empty or duplicate marker {key}"
            seen.add(key)
            assert marker["sites"] and marker["consumers"], marker
            for site in marker["sites"]:
                assert (_REPO / site["file"]).is_file(), f"inventory names a file that does not exist: {site['file']}"

    def test_every_inventoried_marker_is_still_emitted_at_its_level(self):
        failures = []
        for marker in INVENTORY["markers"]:
            found = [s for site in {s["file"] for s in marker["sites"]} for s in envelope.find_marker_sites(_REPO, site, marker["fragments"])]
            levels = [envelope.METHOD_LEVELS[s.method] for s in found if s.method in envelope.METHOD_LEVELS]
            required = marker["required_level"]
            if not found:
                failures.append(f"GONE   {marker['fragments']!r} -- no literal carries it any more; consumers: {marker['consumers']}")
            elif required is not None and (not levels or max(levels) < required):
                failures.append(f"LOWERED {marker['fragments']!r} -- needs a logger call at level >= {required}, found {[(s.file, s.line, s.method) for s in found]}; consumers: {marker['consumers']}")
        assert not failures, "juniper-ml anchors on these markers and will stop matching them:\n" + "\n".join(failures)

    def test_the_resolver_can_say_no(self):
        # Negative controls: a marker emitted nowhere, and a real marker with its fragments swapped
        # (order is part of the contract), must both resolve to NO site.
        target = "src/cascade_correlation/cascade_correlation.py"
        assert envelope.find_marker_sites(_REPO, target, ["P0.4 negative control: emitted nowhere"]) == []
        assert envelope.find_marker_sites(_REPO, target, [" processes", "train_candidates: Executing candidate training with "]) == []
        assert envelope.find_marker_sites(_REPO, target, ["train_candidates: Executing candidate training with ", " processes"]) != []


# ---------------------------------------------------------------------------------------------------
# 4. The checker, against real captures and against broken records
# ---------------------------------------------------------------------------------------------------


class TestEnvelopeChecker:
    @pytest.mark.parametrize("name", sorted(REFERENCE["captures"]))
    def test_reference_captures_classify(self, name):
        lines = (_FIXTURES / name).read_text(encoding="utf-8").splitlines()
        assert len(lines) == REFERENCE["captures"][name]["kept_lines"], f"{name} does not match its provenance record"
        for line in lines:
            # A line that LOOKS like a record (a '+' or a bracketed .py prefix) must classify. A
            # non-record line (a tensor repr continuing the previous record, a warning, uvicorn) may
            # not look like one at all.
            if line.startswith("+") or (line.startswith("[") and ".py:" in line[:80]):
                assert envelope.classify(line)[0] is not None, f"{name}: malformed record {line!r}"
        shapes = sorted({envelope.classify(line)[0] for line in lines} - {None})
        _golden_section("reference_capture_shapes", shapes, subkey=name)

    GOOD = {
        "A_FILE": "+[cascade_correlation.py: fit:2006] (2026-09-22 03:27:56) [INFO] CascadeCorrelationNetwork: fit: Training completed.",
        "A_CONSOLE": "+[candidate_unit.py: 762] (2026-09-22 03:27:45) [INFO] CandidateUnit: train: Epoch 10 - Norm Output: shape=(800,)",
        "STD_FILE_S": "[cascade_correlation.py: fit:2006] (2026-09-22 03:27:56) [INFO] CascadeCorrelationNetwork: fit: Training completed.",
        "STD_FILE_MS": "[monitor.py: on_cascade_add:350] (2026-09-01 05:38:00,489) [INFO] Cascade unit 1 added (correlation=0.0000)",
    }

    def test_good_records_classify(self):
        for shape, line in self.GOOD.items():
            assert envelope.classify(line)[0] == shape, (shape, line)

    @pytest.mark.parametrize(
        "shape,old,new",
        [
            ("A_FILE", "+[", "["),  # sentinel dropped: a Path A record now reads as a stdlib one
            ("A_FILE", "+[", "+ ["),  # sentinel detached
            ("A_FILE", "03:27:56)", "03:27:56,123)"),  # milliseconds added to Path A
            ("A_FILE", "2026-09-22 03:27:56", "2026-09-22T03:27:56"),  # ISO 'T' separator
            ("A_FILE", "(2026-09-22", "(26-09-22"),  # two-digit year
            ("A_FILE", "[INFO]", "INFO:"),  # level bracket lost
            ("A_FILE", " fit:2006]", " fit:]"),  # line number lost
            ("A_FILE", "cascade_correlation.py: fit:2006]", "cascade_correlation.py:2006]"),  # func lost, spacing changed
            ("A_CONSOLE", "(2026-09-22 03:27:45)", "2026-09-22 03:27:45"),  # timestamp parentheses lost
            ("STD_FILE_S", "03:27:56)", "03:27:56.123456)"),  # microseconds
            ("STD_FILE_MS", ",489)", ",48)"),  # truncated milliseconds
        ],
    )
    def test_broken_records_are_rejected(self, shape, old, new):
        good = self.GOOD[shape]
        assert old in good, f"mutation {old!r} does not apply to {good!r}"
        broken = good.replace(old, new, 1)
        assert envelope.classify(broken)[0] != shape, f"checker ACCEPTED a broken {shape} record: {broken!r}"
